<a href="https://colab.research.google.com/github/kang-narae/AI-DL-DA/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%A0%84%EC%B2%98%EB%A6%AC/%EA%B2%B0%EC%B8%A1%EA%B0%92_%EB%B6%84%EB%A5%98_%EC%9B%90%ED%95%AB%EC%9D%B8%EC%BD%94%EB%8D%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 일단 seaborn의 datasets을 불러오자


In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns  #시각화 패키지
from sklearn import preprocessing

In [ ]:
df= sns.load_dataset('titanic')            #sns seaborn에서 데이터셋 불러옴.  데이터프레임 타입임.

  #살았는지 죽었는지 예측하는 거니까, 분류.   그중에서도 2가지 중 예측하는 거니까 이진분류.
print(df)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alo

In [ ]:
print(df.head(10))

   survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes

## 특정 컬럼의 중복값 세기




In [ ]:
nan_deck= df['deck'].value_counts(dropna=False)
print(nan_deck)        #NaN이 안나옴. value_counts는 기본적으로 난을 안 센 값.   dropna=False하면 결측치 nan도 버리지 말고 보여주게 함.

NaN    688
C       59
B       47
D       33
E       32
A       15
F       13
G        4
Name: deck, dtype: int64


In [ ]:
print(type(nan_deck))

<class 'pandas.core.series.Series'>


## dataframe의 각 값이 null인지 확인

In [ ]:
print(df.head().isnull())      #각 값에 null이냐 아니냐 물어본거임. 불린값 반환하지.

   survived  pclass    sex    age  sibsp  parch   fare  embarked  class  \
0     False   False  False  False  False  False  False     False  False   
1     False   False  False  False  False  False  False     False  False   
2     False   False  False  False  False  False  False     False  False   
3     False   False  False  False  False  False  False     False  False   
4     False   False  False  False  False  False  False     False  False   

     who  adult_male   deck  embark_town  alive  alone  
0  False       False   True        False  False  False  
1  False       False  False        False  False  False  
2  False       False   True        False  False  False  
3  False       False  False        False  False  False  
4  False       False   True        False  False  False  


In [ ]:
print(df.head().notnull())

   survived  pclass   sex   age  sibsp  parch  fare  embarked  class   who  \
0      True    True  True  True   True   True  True      True   True  True   
1      True    True  True  True   True   True  True      True   True  True   
2      True    True  True  True   True   True  True      True   True  True   
3      True    True  True  True   True   True  True      True   True  True   
4      True    True  True  True   True   True  True      True   True  True   

   adult_male   deck  embark_town  alive  alone  
0        True  False         True   True   True  
1        True   True         True   True   True  
2        True  False         True   True   True  
3        True   True         True   True   True  
4        True  False         True   True   True  


In [ ]:
print(df.isnull().sum(axis=0))  #row방향, 각 컬럼 기준으로.
#결측값 수 계산한거임

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


## 결측값 많은 컬럼 삭제


In [ ]:
df.dropna(axis=1, thresh=500, inplace=True)  #컬럼기준으로 넌값이 500넘으면 삭제해라.
print(df.columns)      #결측치 500개 넘었던 컬럼인 'deck'가 사라졌음.

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='object')


In [ ]:
df_age = df.dropna(subset=['age'], how='any', axis=0)  
#df에서, age컬럼 중 넌값이 있으면 row 기준으로 삭제하겠다. 그걸 df_age 객체로 만든 거.
df_age.info()    #인덱스는 890까지 있다는 거임. 중간중간 빠지게 된다는 거.

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     714 non-null    int64   
 1   pclass       714 non-null    int64   
 2   sex          714 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        714 non-null    int64   
 5   parch        714 non-null    int64   
 6   fare         714 non-null    float64 
 7   embarked     712 non-null    object  
 8   class        714 non-null    category
 9   who          714 non-null    object  
 10  adult_male   714 non-null    bool    
 11  embark_town  712 non-null    object  
 12  alive        714 non-null    object  
 13  alone        714 non-null    bool    
dtypes: bool(2), category(1), float64(2), int64(4), object(5)
memory usage: 69.2+ KB


## 특정 컬럼의 결측값을 평균값으로 대체하기

In [ ]:
mean_age = df['age'].mean()
print(mean_age)           #df의 mean함수는 알아서 nan값 빼고 계산함.

29.69911764705882


In [ ]:
df['age'].fillna(mean_age, inplace=True) #df의 age컬럼에서 결측값에 앞서 계산한 값인 mean_age를 넣음.
print(df.head(10))           #나이 결측값에 평균값을 넣었음.

   survived  pclass     sex        age  sibsp  parch     fare embarked  \
0         0       3    male  22.000000      1      0   7.2500        S   
1         1       1  female  38.000000      1      0  71.2833        C   
2         1       3  female  26.000000      0      0   7.9250        S   
3         1       1  female  35.000000      1      0  53.1000        S   
4         0       3    male  35.000000      0      0   8.0500        S   
5         0       3    male  29.699118      0      0   8.4583        Q   
6         0       1    male  54.000000      0      0  51.8625        S   
7         0       3    male   2.000000      3      1  21.0750        S   
8         1       3  female  27.000000      0      2  11.1333        S   
9         1       2  female  14.000000      1      0  30.0708        C   

    class    who  adult_male  embark_town alive  alone  
0   Third    man        True  Southampton    no  False  
1   First  woman       False    Cherbourg   yes  False  
2   Third  wom

## 결측값 채우기. (최빈값 / 이전값/ 이후값)



In [ ]:
most_freq= df['embark_town'].value_counts(dropna=True).idxmax()  
 #df의 embark_town컬럼에서 최빈값 찾기
print(most_freq)


Southampton


In [ ]:
df_most_freq = df['embark_town'].fillna(most_freq, inplace=False)  
 # df의 embark_town 컬럼에서 결측값을 most_freq최빈값으로 넣음. 이렇게해서 새로 만들어진 df객체는 그 컬럼 하나만 가지고 있네..      원본 안 건드리려고 inplace=False
print(df_most_freq[825:830])
print(df[825:830])

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829    Southampton
Name: embark_town, dtype: object
     survived  pclass     sex        age  sibsp  parch     fare embarked  \
825         0       3    male  29.699118      0      0   6.9500        Q   
826         0       3    male  29.699118      0      0  56.4958        S   
827         1       2    male   1.000000      0      2  37.0042        C   
828         1       3    male  29.699118      0      0   7.7500        Q   
829         1       1  female  62.000000      0      0  80.0000      NaN   

      class    who  adult_male  embark_town alive  alone  
825   Third    man        True   Queenstown    no   True  
826   Third    man        True  Southampton    no   True  
827  Second  child       False    Cherbourg   yes  False  
828   Third    man        True   Queenstown   yes   True  
829   First  woman       False          NaN   yes   True  


In [ ]:
df['embark_town'].fillna(method='ffill', inplace=True)   #ffill은 결측값을 앞에값으로 채우는 거.   bfill은 뒤에걸로.
print(df['embark_town'][825:830])

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829     Queenstown
Name: embark_town, dtype: object


In [ ]:
print(df.isnull().sum(axis=0))

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64


## 불필요한 컬럼 삭제

In [ ]:
df.drop(['survived', 'embarked'], inplace=True, axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   pclass       891 non-null    int64   
 1   sex          891 non-null    object  
 2   age          891 non-null    float64 
 3   sibsp        891 non-null    int64   
 4   parch        891 non-null    int64   
 5   fare         891 non-null    float64 
 6   class        891 non-null    category
 7   who          891 non-null    object  
 8   adult_male   891 non-null    bool    
 9   embark_town  891 non-null    object  
 10  alive        891 non-null    object  
 11  alone        891 non-null    bool    
dtypes: bool(2), category(1), float64(2), int64(3), object(4)
memory usage: 65.5+ KB


In [ ]:
print(df.isnull().sum(axis=0))

pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64


## 중복제거


In [ ]:
df= pd.DataFrame({'c1':['a','a','b','a','b'],
                  'c2':[1,1,1,2,2],
                  'c3':[1,1,2,2,2]
                  })

print(df)

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2


In [ ]:
df_dup = df.duplicated()   # row 전체가 같으면 중복. df객체에서 중복인 row를 찾기. 불린값으로.
print(df_dup)

0    False
1     True
2    False
3    False
4    False
dtype: bool


In [ ]:
df_dup = df['c2'].duplicated()   #df의 c2컬럼만 보는 것. 중복의 기준은 이전에 나왔느냐이다. 그러니까 맨처음꺼는 중복일 수가 없음.
print(df_dup)

0    False
1     True
2     True
3    False
4     True
Name: c2, dtype: bool


In [ ]:
df2= df.drop_duplicates()            #df에서 중복row 제거한 것.
print(df2)

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2


In [ ]:
df2= df.drop_duplicates(subset=['c2','c3'])   #df에서 c2와 c3 두컬럼의 값이 중복인 걸 제거한 객체 df2.
print(df2)

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2


## 자동차 데이터 불러오자

In [ ]:
df = pd.read_csv('./datasets/auto-mpg.csv', header= None)
#파일을 새로 불러와보자
df.columns = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year', 'origin', 'name']
print(df.head())

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   
2  18.0          8         318.0      150.0  3436.0          11.0          70   
3  16.0          8         304.0      150.0  3433.0          12.0          70   
4  17.0          8         302.0      140.0  3449.0          10.5          70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino  


In [ ]:
mpg_to_kpl = 0.425144
df['kpl']= df['mpg']*mpg_to_kpl
#새 컬럼 만들었음
print(df.head())

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   
2  18.0          8         318.0      150.0  3436.0          11.0          70   
3  16.0          8         304.0      150.0  3433.0          12.0          70   
4  17.0          8         302.0      140.0  3449.0          10.5          70   

   origin                       name       kpl  
0       1  chevrolet chevelle malibu  7.652592  
1       1          buick skylark 320  6.377160  
2       1         plymouth satellite  7.652592  
3       1              amc rebel sst  6.802304  
4       1                ford torino  7.227448  


In [ ]:
df['kpl'] = df['kpl'].round(2)   #소수점처리함
print(df.head())

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   
2  18.0          8         318.0      150.0  3436.0          11.0          70   
3  16.0          8         304.0      150.0  3433.0          12.0          70   
4  17.0          8         302.0      140.0  3449.0          10.5          70   

   origin                       name   kpl  
0       1  chevrolet chevelle malibu  7.65  
1       1          buick skylark 320  6.38  
2       1         plymouth satellite  7.65  
3       1              amc rebel sst  6.80  
4       1                ford torino  7.23  


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object 
 4   weight        398 non-null    float64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   name          398 non-null    object 
 9   kpl           398 non-null    float64
dtypes: float64(5), int64(3), object(2)
memory usage: 31.2+ KB


## 특정 컬럼의 고유값 가져온 후 , 이상값을 nan으로 바꾼 이후 전처리함.



In [ ]:
print(df['horsepower'].unique())

['130.0' '165.0' '150.0' '140.0' '198.0' '220.0' '215.0' '225.0' '190.0'
 '170.0' '160.0' '95.00' '97.00' '85.00' '88.00' '46.00' '87.00' '90.00'
 '113.0' '200.0' '210.0' '193.0' '?' '100.0' '105.0' '175.0' '153.0'
 '180.0' '110.0' '72.00' '86.00' '70.00' '76.00' '65.00' '69.00' '60.00'
 '80.00' '54.00' '208.0' '155.0' '112.0' '92.00' '145.0' '137.0' '158.0'
 '167.0' '94.00' '107.0' '230.0' '49.00' '75.00' '91.00' '122.0' '67.00'
 '83.00' '78.00' '52.00' '61.00' '93.00' '148.0' '129.0' '96.00' '71.00'
 '98.00' '115.0' '53.00' '81.00' '79.00' '120.0' '152.0' '102.0' '108.0'
 '68.00' '58.00' '149.0' '89.00' '63.00' '48.00' '66.00' '139.0' '103.0'
 '125.0' '133.0' '138.0' '135.0' '142.0' '77.00' '62.00' '132.0' '84.00'
 '64.00' '74.00' '116.0' '82.00']


In [ ]:
df['horsepower'].replace('?', np.nan, inplace=True)  #이상값은 일단 nan값으로 바꾼후에 여러가지 연산처리를 함.

## 결측값 있는 row 삭제

In [ ]:
df.dropna(subset=['horsepower'], axis=0, inplace=True)
# horsepower 컬럼 중 결측값이 있는 row를 삭제해라

df['horsepower']= df['horsepower'].astype('float')
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 392 entries, 0 to 397
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64  
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        392 non-null    float64
 5   acceleration  392 non-null    float64
 6   model year    392 non-null    int64  
 7   origin        392 non-null    int64  
 8   name          392 non-null    object 
 9   kpl           392 non-null    float64
dtypes: float64(6), int64(3), object(1)
memory usage: 33.7+ KB


In [ ]:
print(df['horsepower'].unique())

[130. 165. 150. 140. 198. 220. 215. 225. 190. 170. 160.  95.  97.  85.
  88.  46.  87.  90. 113. 200. 210. 193. 100. 105. 175. 153. 180. 110.
  72.  86.  70.  76.  65.  69.  60.  80.  54. 208. 155. 112.  92. 145.
 137. 158. 167.  94. 107. 230.  49.  75.  91. 122.  67.  83.  78.  52.
  61.  93. 148. 129.  96.  71.  98. 115.  53.  81.  79. 120. 152. 102.
 108.  68.  58. 149.  89.  63.  48.  66. 139. 103. 125. 133. 138. 135.
 142.  77.  62. 132.  84.  64.  74. 116.  82.]


## 분류값 가지는 컬럼의 값을 다른 값으로 대체 - 컬럼의 데이터타입 변경

In [ ]:
df['origin'].replace({1:'USA', 2:'EU', 3:'JP'}, inplace=True)
print(df['origin'].unique())
print(df['origin'].value_counts())

['USA' 'JP' 'EU']
USA    245
JP      79
EU      68
Name: origin, dtype: int64


In [ ]:
print(df['origin'].dtypes)

object


In [ ]:
df['origin'] = df['origin'].astype('category')           #카테고리 (분류) 라는 데이터타입이 있음
print(df['origin'].dtypes)
print(df['origin'])

category
0      USA
1      USA
2      USA
3      USA
4      USA
      ... 
393    USA
394     EU
395    USA
396    USA
397    USA
Name: origin, Length: 392, dtype: category
Categories (3, object): ['EU', 'JP', 'USA']


In [ ]:
df['origin'] = df['origin'].astype('str')
print(df['origin'].dtypes)
print(df['origin'])

object
0      USA
1      USA
2      USA
3      USA
4      USA
      ... 
393    USA
394     EU
395    USA
396    USA
397    USA
Name: origin, Length: 392, dtype: object


# 컬럼값 구간 나누기


In [ ]:
count, bin_dividers = np.histogram(df['horsepower'], bins=3)    #3개 구간으로 알아서 나눠줌
print(count)        #마력을 저출력 중출력 고출력 3개 구간으로 나눈거임
print(bin_dividers)    #최소값/ 경계/ 경계 / 최대값 나온 거임.

[257 103  32]
[ 46.         107.33333333 168.66666667 230.        ]


In [ ]:
bin_names=['저출력', '보통출력', '고출력']
df['hp_bin'] = pd.cut(x=df['horsepower'], bins=bin_dividers, labels=bin_names , include_lowest=True  )
#include_lowest면  작은쪽 경계값도 포함하겠다는 것.  107.33333이 나오면 중출력으로 간다는 거.

print(df[['horsepower', 'hp_bin']].head(20))

    horsepower hp_bin
0        130.0   보통출력
1        165.0   보통출력
2        150.0   보통출력
3        150.0   보통출력
4        140.0   보통출력
5        198.0    고출력
6        220.0    고출력
7        215.0    고출력
8        225.0    고출력
9        190.0    고출력
10       170.0    고출력
11       160.0   보통출력
12       150.0   보통출력
13       225.0    고출력
14        95.0    저출력
15        95.0    저출력
16        97.0    저출력
17        85.0    저출력
18        88.0    저출력
19        46.0    저출력


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 392 entries, 0 to 397
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   mpg           392 non-null    float64 
 1   cylinders     392 non-null    int64   
 2   displacement  392 non-null    float64 
 3   horsepower    392 non-null    float64 
 4   weight        392 non-null    float64 
 5   acceleration  392 non-null    float64 
 6   model year    392 non-null    int64   
 7   origin        392 non-null    object  
 8   name          392 non-null    object  
 9   kpl           392 non-null    float64 
 10  hp_bin        392 non-null    category
dtypes: category(1), float64(6), int64(2), object(2)
memory usage: 34.2+ KB


# 라벨인코더와 원핫 인코더

In [ ]:
label_encoder= preprocessing.LabelEncoder()        #LabelEncoder 객체 만들었음. 처음엔 빈 상태임.
onehot_encoder = preprocessing.OneHotEncoder()
#print(label_encoder.classes_)  #에러남. 클래스가 없기 때문임. 아직 객체만 만들었고, 뭘 카테고리로 나누지 않았기 때문에 클래스가 없는 거임.

In [ ]:
hp_bin_labeled= label_encoder.fit_transform(df['hp_bin'].head(15))            #저출력 중출력 고출력을 다시 0 1 2로 바꾼 거임.
#엔코더에게 데이터를 줌 (괄호안에 데이터), 그거 주고나면 fit_transform하면 라벨 붙여주면서 클래스가 생겼고, 이제 클래스 출력이 됨.
#줄바꿈 하고 싶으면 \ 넣으면 됨
print(hp_bin_labeled)
print(type(hp_bin_labeled))   #넘파이객체임
print(label_encoder.classes_)   #이결과로 나온 순서의 인덱스가 0, 1, 2임.


[1 1 1 1 1 0 0 0 0 0 0 1 1 0 2]
<class 'numpy.ndarray'>
['고출력' '보통출력' '저출력']


In [ ]:
#onehot encoder. 머신러닝 학습할 때 이런식으로 바꿔서 제공한다? 
#0 = [1 0 0 0 0 0]
#1 =  [ 0 1 0 0 0 0] ...

print(hp_bin_labeled.shape)


#튜플은 하나만 있어도 뒤에 콤마를 찍었었음..



(15,)


In [ ]:
#hp bin labeled 15개를 각각 리스트로 묶고 원핫인코더로 바꿔준다 ?

hp_bin_labeled= hp_bin_labeled.reshape(-1, 1)             #-1은 니가 알아서 해 라는 의미임.  (-1, 5) 이렇게 하면 (3,5)로 나오는 거임.
print(hp_bin_labeled)


[[1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [2]]


In [ ]:
hp_bin_labeled= hp_bin_labeled.reshape(-1, 1, 3)             #이러면 3차원 행렬.
print(hp_bin_labeled)

[[[1 1 1]]

 [[1 1 0]]

 [[0 0 0]]

 [[0 0 1]]

 [[1 0 2]]]


In [ ]:
hp_bin_labeled= hp_bin_labeled.reshape(-1, 1)             #이제 이걸 원핫인코더에 주자.
print(hp_bin_labeled)

[[1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [2]]


In [ ]:
onehot_pitted = onehot_encoder.fit_transform(hp_bin_labeled)
print(onehot_pitted)

  (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 1)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 1)	1.0
  (12, 1)	1.0
  (13, 0)	1.0
  (14, 2)	1.0


In [ ]:
# 원핫인코더, 희소행렬 표현법.   0번행렬은 1번이(2번이) 값이 1이다  =  (0,1)   1   이렇게 표현
#희소행렬 표현법. 대부분 다 0이기 때문에 0이 아닌 것의 좌표를 알려준 거임.


#예를들어 마지막 14행(15번째)는 2값임. 이거는 [0, 0, 1] 이거지. 그래서 (14,2)에  1이 들어가 있다는 거지.

In [ ]:
df1= df[['horsepower', 'hp_bin']]
df2= pd.get_dummies(df1)
df2

horsepower  hp_bin_저출력  hp_bin_보통출력  hp_bin_고출력
0         130.0           0            1           0
1         165.0           0            1           0
2         150.0           0            1           0
3         150.0           0            1           0
4         140.0           0            1           0
..          ...         ...          ...         ...
393        86.0           1            0           0
394        52.0           1            0           0
395        84.0           1            0           0
396        79.0           1            0           0
397        82.0           1            0           0

[392 rows x 4 columns]

## MinMaxScaler

In [ ]:
from sklearn.preprocessing import StandardScaler                    #sklearn에 통계분석 위한 게 많이 들어있음
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import MinMaxScaler   #최솟값은0 최댓값은1에 맞춰서 비례적으로 바꿔주는 거임.
import numpy as np

data= np.array([4,5,6,7,8])
min= 4
max= 8


In [ ]:
data1= data -4
print(data1)

[0 1 2 3 4]


In [ ]:
data1= data1/4
print(data1)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# data = (data-min)/(max-min)

In [ ]:
minmaxscaler=  MinMaxScaler()
data3 = minmaxscaler.fit_transform(data.reshape(-1,1))
print(data3)


[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]
