In [ ]:
'''
가중합은 벡터의 내적으로 계산한다.
가중치를 곱한 것의 합
벡터를 가중치벡터와 내적.


가중평균은 . ..  
가중치를 곱한 것의 평균.
가중치를 곱한 것의 합(가중합)을 '가중치의 합'으로 나눔.


'''

In [3]:
import numpy as np

x= np.array([[70,75,60]])
x  #2차원 배열인 행벡터.  1x3 행렬

array([[70, 75, 60]])

In [4]:
y= np.array([[2,3,5]])
y   #2차원 배열인 행벡터.

array([[2, 3, 5]])

In [5]:
#x와 y를 내적하자
np.dot(x,y) #에러남. 행이랑 행이잖아.. 행x열 해야되지 내적하려면.

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [6]:
np.dot(x,y.T)   #y를 2차원으로 만들어놨으니까 전치할 수 있지.
#가중합 구한 거임.

array([[665]])

In [7]:
#이제 가중평균 구하자.

y.sum() #가중치합

10

In [8]:
np.dot(x, y.T)/ y.sum()  #가중합을 가중치합으로 나눈 가중평균

array([[66.5]])

In [9]:
'''근데..
1차원 배열인 행벡터끼리는 내적이 예외적으로 됐었지.'''

x=np.array([70,75,60])
y=np.array([2,3,5])
np.dot(x,y)

665