In [ ]:

'''
선형대수의 주인공은 벡터다.
이 벡터를 여러개 묶으면 행렬이고.
엄밀히 말하면 벡터도 행렬이고!

'''


'''
벡터끼리의 덧셈은 차원 (크기)가 같아야함.
덧셈뺄셈은 같은 위치의 성분끼리 계산하니까.  = 요소별 연산.
'''

In [1]:
import numpy as np

#'열'벡터 만들어봅시다
x= np.array([1,2,3,4])  #이건 행벡터고, 행벡터 전치해도 안됨.
x

array([1, 2, 3, 4])

In [3]:
x.T

array([1, 2, 3, 4])

In [5]:
x=np.array([[1,2,3,4]])   #2차원으로 만듦. 그럼 1행4열의 2차원배열인 행렬이 됨.
x.T #그리고 나서 전치 하면 열벡터 됨!

array([[1],
       [2],
       [3],
       [4]])

In [6]:
y= np.array([[10,20,30,40]]).T

In [7]:
y

array([[10],
       [20],
       [30],
       [40]])

In [9]:
x.T+y

array([[11],
       [22],
       [33],
       [44]])

In [11]:
3* x.T

array([[ 3],
       [ 6],
       [ 9],
       [12]])

In [12]:
'''
수학적으로는
원칙적으로는
실수 스칼라와  벡터는 덧셈뺄셈이 안된다. (곱은 됨)
그런데 데이터분석, 프로그래밍 언어에서는
스칼라(실수)와 벡터의 덧셈뺄셈 시
스칼라를 브로드캐스팅 해서 연산하게 함.

왜냐하면
데이터분석 할 때
평균값 빼줄 떄 (?) 브로드캐스팅 연산이 필요하기 때문.

'''

3+ x.T

array([[4],
       [5],
       [6],
       [7]])

In [ ]:

#선형조합
#여러 벡터에 각각 실수배를 한 결과를 더하거나 빼서 새로운 벡터를 만들 수 있다.
#단 이때의 여러 벡터는 동일한 차원이어야 한다.
