In [ ]:
'''
수학에서 벡터는 
면과 면 사이, 선과 선 사이의 각을 구했었음.
기하학, 도형에서의 관점.
평면도형에서는 2차원 벡터,
입체에서는 3차원 벡터.


데이터분석에서의 벡터는
데이터 관점.

벡터 곱셈에는 여러 방법이 있는데, 그 중 내적을 배울 거임.

'''

In [2]:
import numpy as np

x=np.array([[1],[2],[3]])
x

array([[1],
       [2],
       [3]])

In [3]:
y=np.array([[10],[100],[1000]])

In [4]:
y

array([[  10],
       [ 100],
       [1000]])

In [5]:
np.dot(x,y) #에러남.  열벡터 열벡터 곱은 안 됨.

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [6]:
np.dot(x.T,y)

array([[3210]])

In [7]:
x.T@y   #@ (엣)으로도 내적 연산 가능

array([[3210]])

In [9]:
x=np.array([1,2,3]) #행벡터
y=np.array([1000,100,10]) #행벡터

In [10]:
'''벡터의 곱 하려면 행벡터 x 열벡터여야 함 (?)'''

np.dot(x,y)

1230

In [ ]:
'''
엥?
됐네?

원래 안 되는 게 원칙인데
numpy가 1차원 배열끼리도 내적을 계산해 준 거임.
앞에껀 행이고 뒤에껀 열이라고 가정해서 계산 해버림.

'''