In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris
iris=load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
#'feature_names': ['sepal length (cm)',
  #       'sepal width (cm)',
  #      'petal length (cm)',
  #     'petal width (cm)'],    이 네 가지 열.

In [ ]:
'''
스칼라 : 하나의 숫자로 이루어진 데이터
실수 R에 포함된다.
'''

In [3]:
iris.data[0,0]

5.1

In [ ]:
'''
벡터는 스칼라가 모인 것. 특정한 순서가 있다. 
'''

In [4]:
iris.data[0, :]    #벡터임

array([5.1, 3.5, 1.4, 0.2])

In [5]:
# x1 벡터를 만들자

x1= np.array([1,2,3,4,5])
x1   #5차원 벡터

array([1, 2, 3, 4, 5])

In [6]:
x2= np.array([ [1],[2],[3],[4],[5]   ])
#괄호 안에 괄호 넣음. 차원이 하나 더 깊어짐.
x2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
# x1도 x2도 5차원 벡터인데 형태가 다르다.
#x1은 하나의 행으로 된 행벡터.  x2는 하나의 열인  열벡터.
'''
근데 애초에 벡터 설명 열백터로 했잖아. x2.
일반적으로 벡터를 말할 때는 열 벡터를 말하는 거임.

1개의 벡터를 쓸 때는 열벡터가 정석인데, x2가 정석인데.
그런데 여러개의 벡터를 쓸 때는 x1처럼 행벡터로 만들고 붙임.
행벡터도 벡터로 '간주'한다.

일부 머신러닝 프로그램에서는 1개 할 때는 제대로 열벡터로 표현해야만 인식하기도.



근데 x2는 배열 안에 배열 하나 더 들어갔었잖아. 차원이 하나 더 깊어졌었지.
x1은 1차원 배열.
x2는 2차원 배열.

'''

In [7]:
iris= load_iris().data   #150행 x 4열  행렬

iris_sample= iris[0:3,:]
iris_sample

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [8]:
# 3행 4열의 행렬   ...... 그럼 이건 몇차원 배열인 거야 ????

x1= np.array([5.1, 3.5, 1.4, 0.2])
x1

array([5.1, 3.5, 1.4, 0.2])

In [ ]:
# 데이터 레코드 하나만 가져온 x1은 벡터이다.  4차원 벡터.
# x1은 1차원 배열인 행벡터.  그런데 데이터 레코드 하나만 가져올 때는 열벡터로 만들기로 했었지?

In [9]:
x1= x1.reshape(4,1)   #numpy의 매소드 사용해서 4x1의  2차원 배열, 열벡터로 만든다.
x1

array([[5.1],
       [3.5],
       [1.4],
       [0.2]])

In [ ]:
#근데 이거 행렬이지?
'''
4행x1열.  
4차원 열벡터이면서,
2차원 배열이면서...

행렬이기도 하잖아? 열이 1개인 행렬!

즉

벡터도 행렬이 된다.
행벡터는 행이 1개인 행렬이지!
열벡터는 열이 1개인 행렬!



중요한 건
한줄의 레코드를 가져올 때는 열벡터로 만들어야 한다.


'''

In [10]:
x2= np.array([[4.9], [3.] , [1.4], [0.2]])   #차원을 깊게 해서 만든다. 2차원 배열인 열벡터로.
x2

array([[4.9],
       [3. ],
       [1.4],
       [0.2]])

In [13]:
x3= np.array([4.7, 3.2, 1.3, 0.2]).reshape(4,1)
x3


array([[4.7],
       [3.2],
       [1.3],
       [0.2]])

In [14]:
'''벡터를 모아서 행렬로 만들자'''
np.hstack([x1, x2, x3])  #hstack은 가로로 붙이는 것. 이러면 처음의 구조와 달라짐.

array([[5.1, 4.9, 4.7],
       [3.5, 3. , 3.2],
       [1.4, 1.4, 1.3],
       [0.2, 0.2, 0.2]])

In [15]:
#그럼 세로로 붙여보자
 
np.vstack([x1,x2,x3])   #이것도 아님ㅋ

array([[5.1],
       [3.5],
       [1.4],
       [0.2],
       [4.9],
       [3. ],
       [1.4],
       [0.2],
       [4.7],
       [3.2],
       [1.3],
       [0.2]])

In [16]:
#열벡터를 다시 행벡터로 바꾸고 붙여야함.
np.vstack([x1.reshape(1,4),x2.reshape(1,4),x3.reshape(1,4)])

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [17]:
x1   #reshape는 원본에 영향 주는 건 아님.

array([[5.1],
       [3.5],
       [1.4],
       [0.2]])