In [1]:
import numpy as np
np.zeros((3,5))  #3행 5열 행렬이 나옴.모든 원소가 0인..

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [2]:
#np.zeros((N, 1))   #벡터를 만들고 싶으면.. (행렬이 아니고 벡터? 정확히는.. 행렬 중에서 벡터가 아닌 행렬 말고, 벡터.)
#열벡터를 만들려면 열에 1을 넣음
np.zeros((5,1)) #모든 원소가 0인 5차원 열벡터. (2차원 배열.)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [3]:
np.ones((3,1))  #이건 일벡터

array([[1.],
       [1.],
       [1.]])