In [1]:
#전치연산? 행과 열을 바꾼다.
#m행n열에 위치했던 값을 n행m열로 보냄.


import numpy as np
from sklearn.datasets import load_iris
iris=load_iris().data
iris






array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [2]:
iris.shape

(150, 4)

In [3]:
iris_t= iris.T
iris_t  #4행150열.

array([[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
        5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
        5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
        6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
        6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
        6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
        6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
        6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
        7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
        7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
        6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9],
       [3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       

In [4]:
x1= np.array([[1],[2],[3],[4],[5]])   #2차원의 열벡터
x2= np.array([[6],[7],[8],[9],[10]])
x3= np.array([[11],[12],[13],[14],[15]])  

In [6]:
x1

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [7]:
x2

array([[ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [8]:
x3

array([[11],
       [12],
       [13],
       [14],
       [15]])

In [9]:
#하나의 데이터 레코드일 때는 열 벡터
#여러 데이터 레코드를 합칠 때는 열벡터를 행벡터로 바꾸고 붙이기로 했었지
'''
이걸 지난번에는 행벡터로 바꾸고 세로로 vstack으로 붙였었는데
이제는 한번에 전치
'''
x= np.hstack([x1,x2,x3])
x   #일단 열벡터를 reshape 없이 그대로 hstack으로 가로로 바꾸고 전치한다

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [10]:
x.T

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
type(iris)   #다음 휴일에는 넘파이 공부를 해야겠...

numpy.ndarray

In [15]:
iris_1= iris[0, :]   #첫번째 row

In [16]:
iris_1

array([5.1, 3.5, 1.4, 0.2])

In [17]:
# 1행짜리인, 1차원 배열인, 행벡터를 전치하면?

iris_1.T  

array([5.1, 3.5, 1.4, 0.2])

In [ ]:
'''
행벡터 전치한다고 열벡터 되지 않음.
행벡터는 1차원이니까, 행렬로 인식이 안 된 거임. 그래서 전치가 안 됨.
그럼 어떻게 하나면?
'''

In [18]:
iris_2=  np.array([iris_1])
iris_2

array([[5.1, 3.5, 1.4, 0.2]])

In [22]:
'''
괄호 안에 iris_1을 넣었다.
= 즉 차원이 하나 증가했다는 것!
= 2차원이 되었다는 것
= 행렬이라는 거! 
 1행4열의 2차원 배열인 행렬이 됨.'''


#iris_3= [iris_1]   #참고로 이렇게 하면 타입이 리스트가 되네?


iris_2.T  #이제 전치 가능


array([[5.1],
       [3.5],
       [1.4],
       [0.2]])